#!/bin/bash
cmd=strace
if [ ! "$1" ]; then echo "need file name!"; exit 1; fi
if [ "${1##*.}" = 'cc' ]; then tool='g++'; else tool='gcc'; fi
pygmentize -g $1

f=$1; shift
fe=/tmp/${f}.o
fo=/tmp/${f}.txt.log
lib=''
if [ "$1" ] && [ "${1:0:2}" = "-l" ]; then lib=$1; shift; fi

echo "$tool -o $fe ${f} ${lib} -std=c++14" | bash -x
echo "${cmd} $fe $@ 2>$fo" |bash -x

sleep 11 && echo
[ -f $fo ] && pygmentize -g $fo | less -R
