#!/bin/bash
cmd=""
#cmd=strace
if [ ! "$1" ]; then echo "ic fname [-llib]"; exit 1; fi
if [ "${1##*.}" = 'cpp' ]; then tool='g++ -std=c++14'; else tool='gcc'; fi

pygmentize -g $1

f=$1; shift
fe=/tmp/${f}.o
fo=/tmp/${f}.txt.log
lib=''
if [ "$1" ] && [ "${1:0:2}" = "-l" ]; then lib=$1; shift; fi

lib2=`tail -n1 "$f" |grep '//lib' |grep -Po 'p.*$'`
[ "$lib2" ] && lib="$lib -$lib2"

echo "$tool -o $fe ${f} ${lib}" | bash -x
echo "${cmd} $fe $@ 2>$fo" |bash -x

exit

#sleep 11 && echo
#[ -f $fo ] && pygmentize -g $fo | less -R
