#!/bin/bash
. idcommon
pl '$f="/tmp/1"; open my $h, ">", $f; print  $h "hello world"; close $h'
pl '$f="/tmp/1"; open my $h, "<", $f; while(<$h>){ print };    close $h; unlink $f'
py 'f="/tmp/2"; o=open(f,"w"); o.write("hello world"); o.close()'
py 'f="/tmp/2"; o=open(f,"r"); print o.read(); o.close(); import os; os.unlink(f)'
#; print `cat $f`; unlink $f
<<"EOF"
os.system("cat -n " + f)
fob = open(f, 'r')
arr = fob.readlines()
fob.close()
line=raw_input("change the line 3 to:")
arr[2]=line+'\n'
print arr
fob=open(f, 'w')
fob.writelines(arr)
fob.close()
os.system("cat -n " + f)
#starting with Perl 5.6, you can use a "three-argument" open:
  open CONFIG, "<", "dino" or die "Can't open $filename: $!";
  open CONFIG, ">", "dino"
  open CONFIG, ">>","dino"
#  
  open(FH,"lts_help $cfg_type|");
  while (<FH>) { if ($_ =~ /^\s*{(\s*\w+\s*,.*)}\s*\.\s+/) { } } 
  
#capture the return value
  my $success = open LOG, ">>logfile";  
  if ( ! $success) { }

#
  umask 0022;
  open my $fh, '>', '/tmp/1.txt';
  print   $fh        'blahblahblah';
 #print { $fh }      'blahblahblah';
 #select  $fh; print 'blahblahblah';
  close   $fh;

# 
  `chmod  744  '/tmp/1.txt'`;
   chmod 0744, '/tmp/1.txt';
#-------------------------------------------------------------------------------

$f='/etc/hosts'; open my $fh, '<', $f;                  my @a = <$fh>; close $fh; print "@a"
$f='/etc/hosts'; open my $fh, '<', $f; seek($fh, -30, 2); while (<$fh>){ print tell($fh),'-->', $_}; close $fh

#-----------------------------------------------------------------------------
rename ("/usr/runoob/test/file1.txt", "/usr/runoob/test/file2.txt" );
unlink ("/usr/runoob/test/file1.txt");
seek FILEHANDLE, POSITION, WHENCE
tell FILEHANDLE

#!/usr/bin/env eepython
##This example demostrate how to modify a line of a file
##writelines(list)
EOF
