#!/usr/bin/env python
'''
Created on Mar, 2016

@author: eml
'''
#os.system('pygmentize -g ' + sys.argv[0])
#print "=============output============"
from color import *
ebrun('''
a = 60            # 60 = 0011 1100 
b = 13            # 13 = 0000 1101 
c = 0

print a & b;        # 12 = 0000 1100

print a | b;        # 61 = 0011 1101 

print a ^ b;        # 49 = 0011 0001

print ~a;           # -61 = 1100 0011

print a << 2;       # 240 = 1111 0000

print a >> 2;       # 15 = 0000 1111
''')
