#!/usr/bin/env python
'''
Created on Mar, 2016

@author: eml
'''
from color import *
print colors.RED + '''
In if or while condition
values considered false: 
  False
  None
  0, 0L, 0.0, 0j       #zero of any numeric type
  '', (), []           #empty sequence
  {  }                 #empty map
  return 0/False       #instances of user-defined classes, 
                       #if the class defines a __nonzero__() or __len__() method, 
                       #when that method returns the integer zero or bool value False.

All other values are considered true
  so objects of many types are always true.
''' + colors.ENDC
elrun("""
print "true" if 1 else "false"
print "true" if 0 else "false"
print "true" if '' else "false"
print "true" if [] else "false"
print "true" if False else "false"
print "true" if None else "false"

""")
