#!/usr/bin/python
import unittest
import mox
import os
import sys
from datetime import date  
import zoo
os.system('pygmentize -g ' + sys.argv[0])
os.system('pygmentize -g zoo.py')

#sudo easy_install mox
#sudo easy_install nose
class TestZoo(unittest.TestCase):  
    def setUp(self):  
        self.m = mox.Mox()  

    def test_get_most_popular_animal(self):  
        self.m.StubOutWithMock(zoo, 'get_month')  
        zoo.get_month().AndReturn(1)  
        self.m.StubOutWithMock(zoo, 'get_day')  
        zoo.get_day().AndReturn(2)  
      
        self.m.ReplayAll()  
        self.assertEqual('penguin', zoo.get_most_popular_animal())  
        #self.m.VerifyAll()  

    def test_get_most_popular_animal2(self):  
        z = zoo.Zoo()  
        self.m.StubOutWithMock(z, 'get_month')  
        z.get_month().AndReturn(10)  
      
        self.m.ReplayAll()  
        self.assertEqual('tiger', z.get_most_popular_animal())  
        self.m.VerifyAll()  
        

    def tearDown(self):  
        self.m.UnsetStubs()  

unittest.main()
