#!/usr/bin/env python
from color import *
print colors.RED + '''''' + colors.ENDC
ebrun('''
import atexit
assert True, "it is True, so no output"
assert 'tough' in "toughtough"
#Below will throw out AssertionError exception, and exit
assert False, "the result is False."
print "this will not be executed"
''')
